export const rentalColumns = [
  {
    id: 'vehicle.images',
    value: '',
    classes: 'max-w-12 max-h-12 min-w-12 min-h-12',
    type: 'image',
  },
  {
    id: 'vehicleInfo',
    value: 'Vehículo',
    classes: 'w-auto',
    order: 'asc',
    type: 'custom',
  },
  {
    id: 'clientInfo',
    value: 'Cliente',
    classes: 'w-auto',
    order: 'asc',
    type: 'custom',
  },

  {
    id: 'totalCost',
    value: 'Costo Total',
    classes: 'w-auto',
    order: 'asc',
    type: 'currency',
  },
  {
    id: 'status',
    value: 'Estatus de Renta',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'paymentStatus',
    value: 'Estado de Pago',
    classes: 'w-auto',
    order: 'asc',
    type: 'text',
  },
  {
    id: 'files',
    value: 'Archivos',
    classes: 'w-auto',
    order: 'asc',
    type: 'files',
  },
  {
    id: 'startDate',
    value: 'Fecha Inicial',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'endDate',
    value: 'Fecha Final',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'createdAt',
    value: 'F. Creación',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'updatedAt',
    value: 'Fecha. Actualización',
    classes: 'w-auto',
    order: 'asc',
    type: 'date',
  },
  {
    id: 'actions',
    value: 'Acciones',
    classes: 'w-auto',
    type: 'actions',
  },
];
